---
# Handler to handle DB tier notifications

- name: restart mariadb
  service:
    name: mariadb
    enabled: yes
    state: restarted

- name: restart iptables
  service:
    name: iptables
    enabled: yes
    state: restarted
