---
# These tasks install http and the php modules.

- name: Install http and php Debian
  apt:
    name: "{{ item }}" 
    state: latest
  loop: "{{ packageswebd }}"
  when: ansible_os_family == "Debian"

- name: Install http and php RedHat 
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packageswebr }}"
  when: ansible_os_family == "RedHat"


#ESTO ESTA MAL, POR ESO LO COMENTAMOS
#  with_items:
#   - httpd
#   - php
#   - php-mysql
#   - git
#   - libsemanage-python
#   - libselinux-python

#- name: insert iptables rule for httpd
#  lineinfile:
#    dest: /etc/sysconfig/iptables
#    create: yes
#    state: present
#    regexp: "{{ httpd_port }}"
#    insertafter: "^:OUTPUT "
#    line: "-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
#  notify: restart iptables





- name: http service state Debian
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: http service state RedHat
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"


#TRABAJAMOS MUCHO EN TRATAR DE QUE UBUNTU LEVANTE SELINUX Y ENCONTRAMOS QUE NO ESTA APTO AUN PARA ESTE SISTEMA OPERATIVO
#DEBERIAMOS CONFIGURAR APPARMOR PERO COMO NO LO VIMOS EN EL CURSO PREFERIMOS AVANZAR CON OTROS TEMAS PENDIENTES
#- name: Apagar AppArmor
#  service:
#    name: apparmor
#    state: stopped
#  when: ansible_os_family == "Debian"  
#  notify: restart SELINUX

#- name: Iniciar SELinux Ubuntu
#  command: selinux-activate
#  when: ansible_os_family == "Debian"
#  notify: restart SELINUX  


#- name: Enforce SELINUX
#  command: selinux-config-enforcing 
#  when: ansible_os_family == "Debian"
#  notify: restart SELINUX  


# DEBIAN FIREWALL
- name: Comando para negar entradas
  command: sudo ufw default deny incoming
  when: ansible_os_family == "Debian"

- name: Comando para aceptar entradas
  command: sudo ufw default allow outgoing
  when: ansible_os_family == "Debian"


- name: Allow access to port
  ufw:
    rule: allow
    port: '80'
  when: ansible_os_family == "Debian"

- name: Allow access to port
  ufw: 
    rule: allow
    port: '22'
  when: ansible_os_family == "Debian"

- name: Allow access to port
  ufw:
    rule: allow
    port: '443'
  when: ansible_os_family == "Debian"
 

# CENTOS FIREWALL

- name: Allow access to port
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes 
  when: ansible_os_family == "RedHat"





- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes
  when: ansible_selinux.status != 1 and ansible_os_family == "RedHat" 

