---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp RedHat
  yum:
    name: chrony
    state: present
#    tags: ntp
  when: ansible_os_family == "RedHat"  

- name: Install ntp Debian
  apt:
    name: ntp
    state: present 
#    tags: ntp
  when: ansible_os_family == "Debian"
    

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
#    tags: ntp
  when: ansible_os_family == "Debian"
  notify: restart ntp


- name: Cofigure chronyd file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  when: ansible_os_family == "RedHat"
  notify: restart chronyd


- name: Start the ntp service
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"
#  tags: ntp

- name: Start the chrony services
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"


- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
  when: ansible_os_family == "RedHat"
